Models/Employee.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

Controllers/EmployeeController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.Migrations;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebApplication1.Models;

namespace WebApplication1.Controllers
{
    public class EmployeeController : Controller
    {
        private EmployCRUDEntities db = new EmployCRUDEntities();

        // GET: Employee
        public ActionResult Index()
        {
            return View(db.tbl_Employee.ToList());
        }

        // GET: Employee/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tbl_Employee tbl_Employee = db.tbl_Employee.Find(id);
            if (tbl_Employee == null)
            {
                return HttpNotFound();
            }
            return View(tbl_Employee);
        }

        // GET: Employee/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Employee/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,FirstName,LastName,Email,Gender,Password,ConfirmPassword,DOB")] tbl_Employee tbl_Employee)
        {
            if (ModelState.IsValid)
            {
                db.tbl_Employee.Add(tbl_Employee);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(tbl_Employee);
        }

        // GET: Employee/Edit/5
        public ActionResult Edit(int? id)
        {
           if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tbl_Employee tbl_Employee = db.tbl_Employee.Find(id);
            if (tbl_Employee == null)
            {
                return HttpNotFound();
            }
            return View(tbl_Employee);
        }

        // POST: Employee/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.

        public ActionResult Check(int ?Id)

        {
            if (Id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tbl_Employee tbl_Employee = db.tbl_Employee.Find(Id);
            if (tbl_Employee == null)
            {
                return HttpNotFound();
            }
            return View(tbl_Employee);
        }

            [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,FirstName,LastName,Email,Gender,DOB")] tbl_Employee tbl_Employee)

        {

            tbl_Employee tbl_EmployeeExists = db.tbl_Employee.Find(tbl_Employee.Id);
            ModelState.Where(m => m.Key == "Password").FirstOrDefault().Value.Errors.Clear();
            ModelState.Where(m => m.Key == "ConfirmPassword").FirstOrDefault().Value.Errors.Clear();
            if (ModelState.IsValid)
            {
                //db.Entry(tbl_Employee).State = EntityState.Modified;
                //db.tbl_Employee.Remove(tbl_EmployeeExists);
                //db.tbl_Employee.Attach(tbl_Employee);
                tbl_Employee.Password = tbl_EmployeeExists.Password;
                db.Set<tbl_Employee>().AddOrUpdate(tbl_Employee);
                db.Configuration.ValidateOnSaveEnabled = false;
                ///                db.Entry(tbl_Employee).Property(x => x.ConfirmPassword  ).IsModified = false;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(tbl_Employee);
        }

        // GET: Employee/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tbl_Employee tbl_Employee = db.tbl_Employee.Find(id);
            if (tbl_Employee == null)
            {
                return HttpNotFound();
            }
            return View(tbl_Employee);
        }

        // POST: Employee/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            tbl_Employee tbl_Employee = db.tbl_Employee.Find(id);
            db.tbl_Employee.Remove(tbl_Employee);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
        public JsonResult IsAlreadySignedUpEmployee(string EmailId)
        {
            tbl_Employee tbl_Employee = new tbl_Employee();

            using (var context = new EmployCRUDEntities())
            {
                tbl_Employee = context.tbl_Employee.Where(a => a.Email.ToLower() == EmailId.ToLower()).FirstOrDefault();
            }


            bool status;
            if (tbl_Employee != null)
            {
                //Already registered  
                status = false;
            }
            else
            {
                //Available to use  
                status = true;
            }

            return Json(status, JsonRequestBehavior.AllowGet);

        }
    }
}

Views/Employee/Check.cshtml
@model WebApplication1.Models.tbl_Employee

@{
    Layout = null;
    string Editurl = Url.Action("Check", "Edit", new { Id = Model.Id });
}

<!DOCTYPE html>

<html>
<head>
    <link href="//netdna.bootstrapcdn.com/twitter-bootstrap/2.3.2/css/bootstrap-combined.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//netdna.bootstrapcdn.com/twitter-bootstrap/2.3.2/js/bootstrap.min.js"></script>
    <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
    <link href="//netdna.bootstrapcdn.com/twitter-bootstrap/2.3.2/css/bootstrap-combined.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//netdna.bootstrapcdn.com/twitter-bootstrap/2.3.2/js/bootstrap.min.js"></script>
    <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
    <meta name="viewport" content="width=device-width" />
    <title>Edit</title>
    <script type="text/javascript">
        window.onload = function () {
            document.getElementById("Password").value = "";
        };
        function PasswordValidation() {
            if (document.getElementById("Password").value == document.getElementById("CurrentPassword").value) {
                var url = 'https://localhost:44397/Employee/Edit';
                var Uid = document.getElementById("Id").value;
                location.href = url + '/' + Uid;
            }
            else {
                alert("Your password is not Correct!")
            }
        }
    </script>
</head>
<body>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")


    @using (Html.BeginForm("PasswordCheck", "Employee"))
    {
        @Html.ValidationSummary(true, "", new { id = "Id", @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        @Html.TextBoxFor(m => m.Password, new { id = "CurrentPassword", style = "display: none;" })
    <div style="margin:3%">
        <h4>Password Verification</h4>

        <div class="control-group">
            <label class="control-label">Please Enter Your Password to Continue</label>
            <div class="controls">
                    
                @Html.EditorFor(Model => Model.Password, new { id = "Password", htmlattributes = new { @class = "input-xlarge" } })
                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "help-block" })
            </div>
        </div>


        <div class="control-group">
            <div class="controls">
                <input type="button" value="Verify Password" onclick="PasswordValidation()" />

                @* @Html.ActionLink("Check", "Edit", new { Id = Model.Id })*@
            </div>
        </div>
    </div>

    }

    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
</body>
</html>

Views/Employee/Create.cshtml
@model WebApplication1.Models.tbl_Employee

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <link href="//netdna.bootstrapcdn.com/twitter-bootstrap/2.3.2/css/bootstrap-combined.min.css" rel="stylesheet" id="bootstrap-css">
    <link href="//netdna.bootstrapcdn.com/twitter-bootstrap/2.3.2/css/bootstrap-combined.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="~/Scripts/jquery-3.6.0.js"></script>
    <script src="~/Scripts/jquery-3.6.0.min.js"></script>
    <script src="~/Scripts/bootstrap.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>


    <meta name="viewport" content="width=device-width" />
    <title>Create</title>

</head>

<body>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")
    
    
    @using (Html.BeginForm()) 
    {
        @Html.AntiForgeryToken()
        
    <div class="form-horizontal">
        <div id="legend">
            <legend class="">Register</legend>
        </div>
        @Html.ValidationSummary(true, "", new { @class = "help-block" })
        <div class="control-group">
            @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label " })
            <div class="controls">
                @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "input-xlarge" } })
                @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "help-block" })
            </div>
        </div>

        <div class="control-group">
            @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label " })
            <div class="controls">
                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "input-xlarge" } })
                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "help-block" })
            </div>
        </div>

        <div class="control-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label " })
            <div class="controls">
                @Html.TextBoxFor(model => model.Email, new { htmlAttributes = new { @class = "input-xlarge" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "help-block" })
            </div>
        </div>

        <div class="control-group">
            <div class="controls">
                Male:   @Html.RadioButton("Gender", "Male")
                Female: @Html.RadioButton("Gender", "Female")
                @Html.ValidationMessageFor(model => model.Gender, "", new { @class = "help-block" })
            </div>
        </div>

        <div class="control-group">
            @Html.LabelFor(model => model.DOB, htmlAttributes: new { @class = "control-label " })
            <div class="controls">
                @Html.EditorFor(model => model.DOB , "{0:dd/MM/yyyy}", new { @class = "form-control datepicker", placeholder = "DD/MM/YYYY", maxlength = "100" })
                @Html.ValidationMessageFor(model => model.DOB, "", new { @class = "help-block" })
            </div>
        </div>    
        <div class="control-group">
            @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label " })
            <div class="controls">
                @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "input-xlarge" } })
                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "help-block" })
            </div>
        </div>
        <div class="control-group">
            @Html.LabelFor(model => model.ConfirmPassword, htmlAttributes: new { @class = "control-label " })
            <div class="controls">
                @Html.EditorFor(model => model.ConfirmPassword, new { htmlAttributes = new { @class = "input-xlarge" } })
                @Html.ValidationMessageFor(model => model.ConfirmPassword, "", new { @class = "help-block" })
            </div>
        </div>

        <div class="control-group">
            <div class="controls">
                <input type="submit" value="Create" class="btn btn-success" />
            </div>
        </div>
    </div>
    }
    
    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
</body>
</html>

Views/Employee/Create1.cshtml
@model WebApplication1.Models.tbl_Employee

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Create1</title>
</head>
<body>
    @using (Html.BeginForm()) 
    {
        @Html.AntiForgeryToken()
        
        <div class="form-horizontal">
            <h4>tbl_Employee</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.Gender, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Gender, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Gender, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.DOB, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.TextBoxFor(model => model.DOB, "{0:dd/MM/yyyy}", new { @class = "form-control datepicker", placeholder = "DD/MM/YYYY", maxlength = "100" })                    @Html.ValidationMessageFor(model => model.DOB, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </div>
        </div>
    }
    
    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
</body>
</html>

Views/Employee/Delete.cshtml
@model WebApplication1.Models.tbl_Employee

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <link href="//netdna.bootstrapcdn.com/twitter-bootstrap/2.3.2/css/bootstrap-combined.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//netdna.bootstrapcdn.com/twitter-bootstrap/2.3.2/js/bootstrap.min.js"></script>
    <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
    <link href="//netdna.bootstrapcdn.com/twitter-bootstrap/2.3.2/css/bootstrap-combined.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//netdna.bootstrapcdn.com/twitter-bootstrap/2.3.2/js/bootstrap.min.js"></script>
    <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
    <meta name="viewport" content="width=device-width" />
    <title>Delete</title>
</head>
<body>
    <h3>Are you sure you want to delete this?</h3>
    <div>

        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.FirstName)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.FirstName)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.LastName)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.LastName)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Email)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Email)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Gender)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Gender)
            </dd>
    
            @*<dt>
                @Html.DisplayNameFor(model => model.Password)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Password)
            </dd>*@
    
        </dl>
    
        @using (Html.BeginForm()) {
            @Html.AntiForgeryToken()
    
            <div class="form-actions no-color">
                <input type="submit" value="Delete" class="btn btn-default" /> |
                @Html.ActionLink("Back to List", "Index")
            </div>
        }
    </div>
</body>
</html>

Views/Employee/Details.cshtml
@model WebApplication1.Models.tbl_Employee

@{
    Layout = null;
}

<!DOCTYPE html>

<html>  
<head>
    <link href="//netdna.bootstrapcdn.com/twitter-bootstrap/2.3.2/css/bootstrap-combined.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//netdna.bootstrapcdn.com/twitter-bootstrap/2.3.2/js/bootstrap.min.js"></script>
    <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
    <link href="//netdna.bootstrapcdn.com/twitter-bootstrap/2.3.2/css/bootstrap-combined.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//netdna.bootstrapcdn.com/twitter-bootstrap/2.3.2/js/bootstrap.min.js"></script>
    <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
    <meta name="viewport" content="width=device-width" />
    <meta name="viewport" content="width=device-width" />
    <meta name="viewport" content="width=device-width" />
    <title>Details</title>
</head>
<body>
    <div>
        <h4>Details</h4>
        <hr />
        <table class="table table-striped">
            <tr>
            <th>
                @Html.DisplayNameFor(model => model.FirstName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LastName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Gender)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DOB)
            </th>
            </tr>

            <tr>
                <td>
                    @Html.DisplayFor(model => model.FirstName)
                </td>
                <td>
                    @Html.DisplayFor(model => model.LastName)
                </td>
                <td>
                    @Html.DisplayFor(model => model.Email)
                </td>
                <td>
                    @Html.DisplayFor(model => model.Gender)
                </td>
                <td>
                    @Html.DisplayFor(model => model.DOB)
                </td>
            </tr>
            

        </table>
    </div>
    <p>

        @Html.ActionLink("Back to List", "Index")
    </p>
</body>
</html>

Views/Employee/Edit.cshtml
@model WebApplication1.Models.tbl_Employee

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <link href="//netdna.bootstrapcdn.com/twitter-bootstrap/2.3.2/css/bootstrap-combined.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//netdna.bootstrapcdn.com/twitter-bootstrap/2.3.2/js/bootstrap.min.js"></script>
    <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
    <link href="//netdna.bootstrapcdn.com/twitter-bootstrap/2.3.2/css/bootstrap-combined.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//netdna.bootstrapcdn.com/twitter-bootstrap/2.3.2/js/bootstrap.min.js"></script>
    <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
    <meta name="viewport" content="width=device-width" />
    <title>Edit</title>
    <script type="text/javascript">
        window.onload = function () {
            var DOBValue = document.getElementById("DOBValue").value;
            var FormatedDOB = new Date(DOBValue).toISOString().substring(0, 10);
            document.getElementById("DOB").value = FormatedDOB;
            var GenderValue = document.getElementById("GenderValue").value;
            Male = document.getElementsByClassName(GenderValue);
            Male[0].checked = true;
        };
        $('#DOB').datepicker({
            onSelect: function () {
                $('#data').text(this.value);
            }
        });
        //function GetGender(Gender) {
        //    if (GenderValue == Gender) {
        //        return true;
        //    }
        //    return false;
        //}
    </script>
</head>
<body>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")


    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>tbl_Employee</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)
        @Html.TextBoxFor(m => m.Gender, new { id = "GenderValue", style = "display: none;" })
        @Html.TextBoxFor(m => m.DOB, new { id = "DOBValue", style = "display: none;" })

        <div class="form-group">
            @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="controls">
                @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "input-xlarge" } })
                @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "help-block" })
            </div>
        </div>

        <div class="control-group">
            @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label " })
            <div class="controls">
                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "input-xlarge" } })
                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "help-block" })
            </div>
        </div>

        <div class="control-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label " })
            <div class="controls">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "input-xlarge" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "help-block" })
            </div>
        </div>

        <div class="control-group">
            @Html.LabelFor(model => model.Gender, htmlAttributes: new { @class = "control-label " })
            <div class="controls">
                Male:   @Html.RadioButton("Gender", "Male", htmlAttributes: new { @class = "Male " })
                Female: @Html.RadioButton("Gender", "Female", htmlAttributes: new { @class = "Female " })
                @Html.ValidationMessageFor(model => model.Gender, "", new { @class = "help-block" })
            </div>
        </div>
        <div class="control-group">
            @Html.LabelFor(model => model.DOB, htmlAttributes: new { @class = "control-label " })
            <div class="controls">
                @Html.EditorFor(model => model.DOB, "{0:dd/MM/yyyy}", new { @class = "form-control datepicker", placeholder = "DD/MM/YYYY", maxlength = "100" })
                @Html.ValidationMessageFor(model => model.DOB, "", new { @class = "help-block" })
            </div>
        </div>

        @*<div class="control-group">
            @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label " })
            <div class="controls">
                @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "input-xlarge" } })
                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "help-block" })
            </div>
        </div>*@
        @*<div class="control-group">
            @Html.LabelFor(model => model.ConfirmPassword, htmlAttributes: new { @class = "control-label " })
            <div class="controls">
                @Html.EditorFor(model => model.ConfirmPassword, new { htmlAttributes = new { @class = "input-xlarge" } })
                @Html.ValidationMessageFor(model => model.ConfirmPassword, "", new { @class = "help-block" })
            </div>
        </div>*@

        <div class="control-group">
            <div class="controls">
                <input type="submit" value="Save" class="btn btn-success" />
            </div>
        </div>
    </div>
    }

    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
</body>
</html>

Views/Employee/Index.cshtml
@model IEnumerable<WebApplication1.Models.tbl_Employee>

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <link href="//netdna.bootstrapcdn.com/twitter-bootstrap/2.3.2/css/bootstrap-combined.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//netdna.bootstrapcdn.com/twitter-bootstrap/2.3.2/js/bootstrap.min.js"></script>
    <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
    <link href="//netdna.bootstrapcdn.com/twitter-bootstrap/2.3.2/css/bootstrap-combined.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//netdna.bootstrapcdn.com/twitter-bootstrap/2.3.2/js/bootstrap.min.js"></script>
    <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
    <meta name="viewport" content="width=device-width" />   
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
    <p>
        @Html.ActionLink("Create New", "Create")
    </p>
    <table class="table table-striped">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.FirstName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LastName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Gender)
            </th>    
            <th>
                @Html.DisplayNameFor(model => model.DOB)
            </th>

            <th></th>
        </tr>
    
    @foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.FirstName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LastName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Gender)
            </td>      
            <td>
                @Html.DisplayFor(modelItem => item.DOB)
            </td>

            <td>
                @Html.ActionLink("Edit", "Check", new { id=item.Id }) |
                @Html.ActionLink("Details", "Details", new { id=item.Id }) |
                @Html.ActionLink("Delete", "Delete", new { id=item.Id })
            </td>
        </tr>
    }
    
    </table>
</body>
</html>